#
# This module is automatically generated by the gen-valid-commands.pl script
#


package Bio::KBase::InvocationService::ValidCommands;

use strict;

require Exporter;

our @ISA = qw(Exporter);
our @EXPORT_OK = qw(valid_commands command_groups modules);

our @command_groups = (
   { name => 'invocation', title => 'Invocation Service Commands', items => [
	{ cmd => 'invocation_info', link => '' },
   ]},
);

our @modules = (
	'invocation',
);

sub command_groups
{
    return \@command_groups;
}

sub modules
{
    return \@modules;
}

sub valid_commands
{
    my %v;
    for my $g (@command_groups)
    {
	$v{$_} = 1 foreach map { $_->{cmd} } @{$g->{items}};
    }
    return \%v;
}

1;




